# Generated by Django 5.1.6 on 2025-03-14 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('scheduler', '0002_scheduledtask_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
