# Generated by Django 5.1.7 on 2025-03-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_scheduledtask_content_type_scheduledtask_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='activation_method',
            field=models.CharField(choices=[('set_active', 'Set Active'), ('activate_with_notification', 'Activate with Notification'), ('activate_with_log', 'Activate with Log'), ('activate_with_welcome_email', 'Activate with Welcome Email')], default='set_active', max_length=50),
        ),
    ]
